
category = Category.create(name: 'Electronics')
category = Category.create(name: 'Books')
category = Category.create(name: 'Games')
category = Category.create(name: 'Nokia',parent_id: 1)
category = Category.create(name: 'Micromax',parent_id: 1)
category = Category.create(name: 'Samsung',parent_id: 1)
category = Category.create(name: 'HTC',parent_id: 1)
category = Category.create(name: 'Children Books',parent_id: 2)
category = Category.create(name: 'Music Books',parent_id: 2)
category = Category.create(name: 'Indoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)

category = Category.create(name: 'outdoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)
category = Category.create(name: 'outdoor Games',parent_id: 3)
